// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "test.h"

Fl_Menu_Item LogicWindow::menu_[] = {
 {"submenu", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

LogicWindow::LogicWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(726, 642, "Logic");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 0, 726, 605);
      { Fl_Scroll* o = new Fl_Scroll(460, 50, 225, 425, "logic elements");
        o->type(2);
        { new Fl_Button(485, 75, 140, 35, "\320\273\320\276\320\263\320\270\321\207\320\265\321\201\320\272\320\276\320\
\265 \320\230");
        } // Fl_Button* o
        { new Fl_Button(490, 370, 140, 35, "\320\273\320\276\320\263\320\270\321\207\320\265\321\201\320\272\320\276\320\
\265 \320\230\320\233\320\230");
        } // Fl_Button* o
        { new Fl_Button(485, 235, 140, 35, "\320\270\321\201\321\202\320\276\321\207\320\275\320\270\320\272");
        } // Fl_Button* o
        o->end();
      } // Fl_Scroll* o
      { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 726, 20, "\320\274\320\265\320\275\321\216");
      } // Fl_Menu_Bar* o
      { Fl_Menu_Button* o = new Fl_Menu_Button(0, 0, 69, 20, "\321\204\320\260\320\271\320\273");
        o->menu(menu_);
      } // Fl_Menu_Button* o
      { new Fl_Box(50, 64, 385, 386, "\320\277\320\276\320\273\320\265");
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
}
