// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Scroll.H>

class LogicWindow
{
public:
  LogicWindow();
  static Fl_Menu_Item menu_[];
};
#endif
